import {defaultOptions,type PrimeVueLocaleOptions} from 'primevue/config';
import {ui_locale} from './i18n';

// PrimeVue keeps these templates (including {page}/{0}) in its own formatter.
const chinese={
  startsWith:'开头为',contains:'包含',notContains:'不包含',endsWith:'结尾为',equals:'等于',notEquals:'不等于',noFilter:'不筛选',lt:'小于',lte:'小于或等于',gt:'大于',gte:'大于或等于',dateIs:'日期为',dateIsNot:'日期不为',dateBefore:'日期早于',dateAfter:'日期晚于',clear:'清除',apply:'应用',matchAll:'全部匹配',matchAny:'任意匹配',addRule:'添加规则',removeRule:'移除规则',accept:'是',reject:'否',choose:'选择',upload:'上传',cancel:'取消',completed:'已完成',pending:'等待中',
  dayNames:['星期日','星期一','星期二','星期三','星期四','星期五','星期六'],dayNamesShort:['周日','周一','周二','周三','周四','周五','周六'],dayNamesMin:['日','一','二','三','四','五','六'],monthNames:['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],monthNamesShort:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],chooseYear:'选择年份',chooseMonth:'选择月份',chooseDate:'选择日期',prevDecade:'上十年',nextDecade:'下十年',prevYear:'上一年',nextYear:'下一年',prevMonth:'上个月',nextMonth:'下个月',prevHour:'上一小时',nextHour:'下一小时',prevMinute:'上一分钟',nextMinute:'下一分钟',prevSecond:'上一秒',nextSecond:'下一秒',am:'上午',pm:'下午',today:'今天',weekHeader:'周',firstDayOfWeek:1,showMonthAfterYear:true,dateFormat:'yy/mm/dd',weak:'弱',medium:'中',strong:'强',passwordPrompt:'请输入密码',emptyFilterMessage:'未找到结果',searchMessage:'共有 {0} 个结果',selectionMessage:'已选择 {0} 项',emptySelectionMessage:'未选择项目',emptySearchMessage:'未找到结果',fileChosenMessage:'{0} 个文件',noFileChosenMessage:'未选择文件',emptyMessage:'没有可用选项',
  aria:{trueLabel:'是',falseLabel:'否',nullLabel:'未选择',star:'1 星',stars:'{star} 星',selectAll:'已全选',unselectAll:'已清空选择',close:'关闭',previous:'上一个',next:'下一个',navigation:'导航',scrollTop:'回到顶部',moveTop:'移到顶部',moveUp:'上移',moveDown:'下移',moveBottom:'移到底部',moveToTarget:'移到目标',moveToSource:'移到来源',moveAllToTarget:'全部移到目标',moveAllToSource:'全部移到来源',pageLabel:'第 {page} 页',firstPageLabel:'首页',lastPageLabel:'末页',nextPageLabel:'下一页',prevPageLabel:'上一页',rowsPerPageLabel:'每页行数',jumpToPageDropdownLabel:'跳转页码选择',jumpToPageInputLabel:'跳转页码输入',selectRow:'已选择行',unselectRow:'未选择行',expandRow:'已展开行',collapseRow:'已折叠行',showFilterMenu:'显示筛选菜单',hideFilterMenu:'隐藏筛选菜单',filterOperator:'筛选运算符',filterConstraint:'筛选条件',editRow:'编辑行',saveEdit:'保存编辑',cancelEdit:'取消编辑',listView:'列表视图',gridView:'网格视图',slide:'幻灯片',slideNumber:'{slideNumber}',zoomImage:'缩放图片',zoomIn:'放大',zoomOut:'缩小',rotateRight:'向右旋转',rotateLeft:'向左旋转',listLabel:'选项列表'}
};
const english=defaultOptions.locale as PrimeVueLocaleOptions;
export function primevue_locale():PrimeVueLocaleOptions{return ui_locale.value==='zh-CN'?{...english,...chinese,aria:{...english.aria,...chinese.aria}}:{...english,aria:{...english.aria}};}
