<script setup lang="ts">
import { computed, ref } from 'vue';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Dialog from 'primevue/dialog';
import Checkbox from 'primevue/checkbox';
import { api, data, ui, route, navigate, connectedNetworks, isConnected, perform, notice, deviceName, modelLabel, addNetwork, newSession } from '../ui';
import { subnetLabel, networkStatus } from '../network';
import type { Network } from '../domain';
defineProps<{ section: string }>();
const query = ref('');
const network = computed(() => data.value.networks.find(n => n.id === route.value.split('/')[2]));
const devices = computed(() => { const n = network.value; if (!n) return []; const remotes = data.value.devices.filter(d => d.network_id === n.id && d.id !== 'local'); const local = data.value.devices.find(d => d.id === 'local'); return local && n.connection_status === 'connected' ? [{ ...local, network_id: n.id, ip: n.local_ip ?? '待获取' }, ...remotes] : remotes; });
const visibleServices = computed(() => data.value.services.filter(s => (isConnected(s.network_id) || (s.device_id === 'local' && !s.network_id)) && `${s.name} ${deviceName(s.device_id)}`.includes(query.value)));
const device = computed(() => devices.value.find(d => d.id === ui.deviceDetail));
const syncSelection = ref<string[]>([]);
function connect(nid: string) { perform(() => api.connectNetwork(nid)); }
function disconnect(nid: string) { perform(() => api.disconnectNetwork(nid)); }
const hasConnection = (n: Network) => ['connected', 'waiting_dhcp'].includes(n.connection_status);
function remove(nid: string) { if (window.confirm('删除本机保存的网络配置？此操作不销毁其他设备上的网络。')) perform(() => api.deleteNetwork(nid)); }
function sync() { const result = perform(() => { api.syncModels(ui.deviceDetail, syncSelection.value); return true; }); if (result) { notice('一次性同步演示完成，目标设备独立保存；未传输任何真实密钥。'); syncSelection.value = []; } }
</script>
<template>
  <div class="page-container">
    <template v-if="section === 'services'"><div class="page-heading"><div><span class="eyebrow">READY WHEN YOU ARE</span><h1>你的服务，随处可达。</h1><p class="muted">所有已连接网络的应用入口。部署和管理，只需在会话里说一声。</p></div><span class="count-badge">{{ visibleServices.length }} 个服务</span></div><div class="search-field"><i aria-hidden="true" class="pi pi-search"/><InputText v-model="query" aria-label="搜索服务" placeholder="搜索服务或设备…"/></div><div class="service-grid"><article v-for="service in visibleServices" :key="service.id" class="service-card"><div class="row-between"><span class="resource-icon" :class="service.kind"><i aria-hidden="true" :class="`pi ${service.kind === 'music' ? 'pi-headphones' : service.kind === 'files' ? 'pi-folder' : 'pi-code'}`"/></span><span class="status-label" :class="{ bad: !service.reachable }"><span class="status-dot" :class="{ off: !service.reachable }"/>{{ service.reachable ? '可访问' : '不可达' }}</span></div><h2>{{ service.name }}</h2><p><i aria-hidden="true" class="pi pi-desktop"/> {{ deviceName(service.device_id) }} · {{ data.networks.find(n => n.id === service.network_id)?.name ?? '本机' }}</p><code>{{ service.address }}</code><Button :label="service.reachable ? '打开服务' : '暂不可访问'" :disabled="!service.reachable" icon="pi pi-arrow-up-right" icon-pos="right" outlined @click="ui.servicePreview = service.id"/></article></div><div v-if="!visibleServices.length" class="empty-state"><i aria-hidden="true" class="pi pi-th-large"/><h2>{{ connectedNetworks.length ? '还没有找到服务' : '先连接一个网络' }}</h2><p>连接网络后查看服务，或通过会话让设备准备一个新服务。</p><Button label="前往会话" outlined @click="navigate('/sessions')"/></div><div class="bottom-note"><i aria-hidden="true" class="pi pi-comments"/><span>想安装、修改或移除服务？告诉本机的 rove-agent 即可。</span></div></template>
    <template v-else-if="network"><Button label="返回网络列表" icon="pi pi-arrow-left" text @click="navigate('/networks')"/><div class="page-heading"><div><span class="eyebrow">NETWORK SPACE</span><h1>{{ network.name }}</h1><p class="muted">虚拟网段 {{ subnetLabel(network) }} · {{ networkStatus(network) }}</p></div><Button label="网络名片" icon="pi pi-qrcode" outlined @click="ui.shareNetwork = network.id"/></div><p v-if="network.connection_error" role="alert" class="form-error">{{ network.connection_error }}</p><div class="resource-actions"><Button :label="hasConnection(network) ? '断开网络' : '连接网络'" outlined @click="hasConnection(network) ? disconnect(network.id) : connect(network.id)"/></div><div class="section-heading"><h2>设备</h2><span class="count-badge">{{ devices.length }} 个节点</span></div><div class="device-grid"><button v-for="d in devices" :key="d.id" class="device-card" @click="ui.deviceDetail = d.id; syncSelection = []"><span class="resource-icon"><i aria-hidden="true" :class="`pi ${d.os === 'Android' ? 'pi-tablet' : 'pi-desktop'}`"/></span><strong>{{ d.name }}</strong><span>{{ d.os }} · {{ d.ip }}</span><span class="status-label" :class="{ bad: !d.online || !isConnected(network.id) }">{{ d.online && isConnected(network.id) ? '已连接' : '不可达' }}</span><small>{{ d.online && isConnected(network.id) ? '延迟 12 ms · ↑ 1.2 KB/s · ↓ 4.8 KB/s（演示）' : '连接后更新状态' }}</small></button></div><div v-if="!devices.length" class="empty-state"><h2>这里还没有设备</h2><p>连接此网络，或把网络名片分享给另一台设备。</p></div></template>
    <template v-else><div class="page-heading"><div><span class="eyebrow">CONNECTED, ON YOUR TERMS</span><h1>属于你的漫游空间。</h1><p class="muted">可同时连接多个网络，虚拟网段不能重叠。每台设备都是对等的。</p></div><Button label="添加网络" icon="pi pi-plus" @click="addNetwork"/></div><div class="network-list"><article v-for="n in data.networks" :key="n.id" class="network-row"><button class="network-open" @click="navigate(`/networks/${n.id}`)"><span class="resource-icon"><i aria-hidden="true" class="pi pi-share-alt"/></span><span><strong>{{ n.name }}</strong><small>{{ subnetLabel(n) }} · {{ networkStatus(n) }}</small></span><i aria-hidden="true" class="pi pi-angle-right"/></button><div class="resource-actions"><Button :label="hasConnection(n) ? '断开' : '连接'" :outlined="hasConnection(n)" @click="hasConnection(n) ? disconnect(n.id) : connect(n.id)"/><Button icon="pi pi-qrcode" text :aria-label="`分享${n.name}`" @click="ui.shareNetwork = n.id"/><Button icon="pi pi-pencil" text :aria-label="`编辑${n.name}`" @click="ui.editNetwork = n.id; ui.networkDialog = true"/><Button icon="pi pi-trash" text severity="secondary" :aria-label="`删除${n.name}`" @click="remove(n.id)"/></div><p v-if="n.connection_error" role="alert" class="form-error network-error">{{ n.connection_error }}</p></article></div><div v-if="!data.networks.length" class="empty-state"><i aria-hidden="true" class="pi pi-compass"/><h2>为设备建立一个共同空间</h2><p>创建自己的网络，或用另一台设备分享的名片加入。</p><Button label="加入已有网络" outlined @click="ui.joinDialog = true"/></div><div class="bottom-note"><i aria-hidden="true" class="pi pi-shield"/><span>网络名片包含入网密钥。加入网络即获得设备控制与服务访问能力。</span></div></template>
    <Dialog :visible="!!device" modal header="设备详情" @update:visible="ui.deviceDetail = ''" :style="{ width: '32rem' }" :breakpoints="{ '640px': '94vw' }"><div v-if="device" class="stack-form"><h2>{{ device.name }}</h2><p>{{ device.os }} · {{ device.ip }}</p><span>{{ device.online && isConnected(device.network_id) ? '已连接（演示）' : '设备不可达' }}</span><h3>同步本机模型配置</h3><p class="muted">一次性复制选定型号和所需连接配置，目标独立保存。正式功能会包含凭据，请仅同步给信任的设备。</p><label v-for="m in data.models" :key="m.id" class="check-row"><Checkbox v-model="syncSelection" :value="m.id" :input-id="`sync-${m.id}`"/>{{ modelLabel(m.id) }}</label><Button label="模拟同步选中配置" :disabled="!syncSelection.length" @click="sync"/><small>目标已配置 {{ device.model_ids.length }} 个型号。此处不建立远程会话。</small></div></Dialog>
  </div>
</template>
